import { Router, Request, Response } from 'express';
import prisma from '../lib/prisma';
import multer from 'multer';
import path from 'path';
import fs from 'fs';

// Configure multer storage for Serverless (Memory)
const storage = multer.memoryStorage();
const upload = multer({ 
  storage,
  limits: { fileSize: 2 * 1024 * 1024 } // Limit file size to 2MB
});

const router = Router();

// GET /api/documents - Ambil semua dokumen (dengan filter opsional)
router.get('/', async (req: Request, res: Response) => {
  try {
    const { tipe, status, archived } = req.query;

    const where: Record<string, any> = {};
    if (tipe) where.tipe = tipe as string;
    if (status) where.status = status as string;
    // Filter by archived status: 'true' = archived only, default = non-archived
    where.isArchived = archived === 'true' ? true : false;

    const documents = await prisma.document.findMany({
      where,
      select: {
        id: true, noBerkas: true, judul: true, nik: true, lokasi: true, tipe: true, 
        deadline: true, status: true, klasifikasi: true, keamanan: true, fileUrl: true, 
        isArchived: true, fileMimeType: true,
        authorId: true, createdAt: true, updatedAt: true,
        author: { select: { id: true, name: true, email: true } }
      },
      orderBy: { createdAt: 'desc' },
    });

    res.json(documents);
  } catch (error) {
    console.error('Get documents error:', error);
    res.status(500).json({ error: 'Terjadi kesalahan pada server.' });
  }
});

// POST /api/documents - Buat dokumen baru
router.post('/', upload.single('file'), async (req: Request, res: Response) => {
  try {
    const { noBerkas, judul, nik, lokasi, deadline, tipe, status, klasifikasi, keamanan, authorId } = req.body;

    if (!noBerkas || !tipe || !authorId) {
      res.status(400).json({ error: 'noBerkas, tipe, dan authorId wajib diisi.' });
      return;
    }

    let fileData = null;
    let fileMimeType = null;
    let fileUrl = null;

    if (req.file) {
      fileData = req.file.buffer;
      fileMimeType = req.file.mimetype;
    }

    const document = await prisma.document.create({
      data: { 
        noBerkas, judul, nik, lokasi, deadline: deadline ? new Date(deadline) : null, tipe, status, klasifikasi, keamanan, authorId, 
        fileData, fileMimeType, fileUrl 
      },
    });

    if (fileData) {
      // Update fileUrl using the actual document ID generated by database
      await prisma.document.update({
        where: { id: document.id },
        data: { fileUrl: `/api/documents/${document.id}/file` }
      });
      document.fileUrl = `/api/documents/${document.id}/file`;
    }

    // Don't send massive binary data back in JSON
    const { fileData: _, ...docWithoutData } = document as any;
    res.status(201).json(docWithoutData);
  } catch (error) {
    console.error('Create document error:', error);
    res.status(500).json({ error: 'Terjadi kesalahan pada server.' });
  }
});

// GET /api/documents/stats - Statistik dashboard
router.get('/stats', async (req: Request, res: Response) => {
  try {
    const { tipe } = req.query;

    const where: Record<string, string> = {};
    if (tipe) where.tipe = tipe as string;

    const total = await prisma.document.count({ where });
    const proses = await prisma.document.count({ where: { ...where, status: 'proses' } });
    const selesai = await prisma.document.count({ where: { ...where, status: 'selesai' } });
    const error = await prisma.document.count({ where: { ...where, status: 'error' } });

    res.json({ total, proses, selesai, error });
  } catch (error) {
    console.error('Stats error:', error);
    res.status(500).json({ error: 'Terjadi kesalahan pada server.' });
  }
});

// GET /api/documents/global-stats - Statistik grafik
router.get('/global-stats', async (req: Request, res: Response) => {
  try {
    const sengketaCount = await prisma.document.count({ where: { tipe: 'sengketa' } });
    const sengketaSelesai = await prisma.document.count({ where: { tipe: 'sengketa', status: 'selesai' } });
    const perkaraCount = await prisma.document.count({ where: { tipe: 'perkara' } });
    const perkaraProses = await prisma.document.count({ where: { tipe: 'perkara', status: 'proses' } });
    
    // Get the last 5 days including today
    const dates = Array.from({ length: 5 }).map((_, i) => {
      const d = new Date();
      d.setDate(d.getDate() - (4 - i));
      return d;
    });

    const trend = { sengketa: [0,0,0,0,0], perkara: [0,0,0,0,0] };

    // Fetch all documents from the last 5 days
    const fiveDaysAgo = new Date();
    fiveDaysAgo.setDate(fiveDaysAgo.getDate() - 5);
    
    const recentDocs = await prisma.document.findMany({
      where: { createdAt: { gte: fiveDaysAgo } },
      select: { tipe: true, createdAt: true }
    });

    recentDocs.forEach(doc => {
      const docDate = new Date(doc.createdAt).setHours(0,0,0,0);
      dates.forEach((date, i) => {
        if (date.setHours(0,0,0,0) === docDate) {
          if (doc.tipe === 'sengketa') trend.sengketa[i]++;
          else if (doc.tipe === 'perkara') trend.perkara[i]++;
        }
      });
    });

    res.json({ sengketaCount, sengketaSelesai, perkaraCount, perkaraProses, trend });
  } catch (error) {
    res.status(500).json({ error: 'Server error' });
  }
});

// GET /api/documents/export - Ekspor data ke CSV
router.get('/export', async (req: Request, res: Response) => {
  try {
    const { tipe } = req.query;
    const where: Record<string, string> = {};
    if (tipe) where.tipe = tipe as string;

    const documents = await prisma.document.findMany({
      where,
      include: { author: { select: { name: true } } },
      orderBy: { createdAt: 'desc' },
    });

    // Generate CSV
    const header = 'No,No Berkas,Judul,NIK/NIB,Lokasi,Tipe,Status,Klasifikasi,Keamanan,Petugas,Tanggal';
    const rows = documents.map((doc, i) =>
      `${i + 1},"${doc.noBerkas}","${doc.judul}","${doc.nik || '-'}","${doc.lokasi}","${doc.tipe}","${doc.status}","${doc.klasifikasi}","${doc.keamanan}","${doc.author.name}","${doc.createdAt.toISOString().split('T')[0]}"`
    );
    const csv = [header, ...rows].join('\n');

    res.setHeader('Content-Type', 'text/csv; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="export_documents_${tipe || 'all'}.csv"`);
    res.send(csv);
  } catch (error) {
    console.error('Export error:', error);
    res.status(500).json({ error: 'Terjadi kesalahan pada server.' });
  }
});

// GET /api/documents/:id/file - Serve binary file data
router.get('/:id/file', async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const document = await prisma.document.findUnique({
      where: { id }
    });

    if (!document || !document.fileData) {
      res.status(404).json({ error: 'File tidak ditemukan' });
      return;
    }

    res.setHeader('Content-Type', document.fileMimeType || 'application/pdf');
    res.send(document.fileData);
  } catch (error) {
    console.error('Fetch file error:', error);
    res.status(500).json({ error: 'Gagal mengambil file' });
  }
});

// PUT /api/documents/:id - Update dokumen (status, klasifikasi, dll)
router.put('/:id', async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const { status, klasifikasi, keamanan, judul, nik, lokasi, deadline, isArchived } = req.body;

    const updateData: Record<string, any> = {};
    if (status) updateData.status = status;
    if (klasifikasi) updateData.klasifikasi = klasifikasi;
    if (keamanan) updateData.keamanan = keamanan;
    if (judul) updateData.judul = judul;
    if (nik !== undefined) updateData.nik = nik;
    if (lokasi) updateData.lokasi = lokasi;
    if (deadline) updateData.deadline = new Date(deadline);
    if (typeof isArchived === 'boolean') updateData.isArchived = isArchived;

    const document = await prisma.document.update({
      where: { id },
      data: updateData,
      select: {
        id: true, noBerkas: true, judul: true, nik: true, lokasi: true, deadline: true, tipe: true,
        status: true, klasifikasi: true, keamanan: true, fileUrl: true,
        isArchived: true, fileMimeType: true,
        authorId: true, createdAt: true, updatedAt: true,
        author: { select: { id: true, name: true, email: true } }
      },
    });

    res.json(document);
  } catch (error) {
    console.error('Update document error:', error);
    res.status(500).json({ error: 'Gagal mengupdate dokumen' });
  }
});

// DELETE /api/documents/:id - Hapus dokumen
router.delete('/:id', async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    await prisma.document.delete({ where: { id } });
    res.status(200).json({ message: 'Dokumen berhasil dihapus' });
  } catch (error) {
    console.error('Delete error:', error);
    res.status(500).json({ error: 'Gagal menghapus dokumen' });
  }
});

export default router;
