import { Router, Request, Response } from 'express';
import prisma from '../lib/prisma';
import multer from 'multer';
import path from 'path';
import fs from 'fs';

// Configure multer storage for Serverless (Memory)
const storage = multer.memoryStorage();
const upload = multer({ 
  storage,
  limits: { fileSize: 2 * 1024 * 1024 } // Limit file size to 2MB
});

const router = Router();

// GET /api/documents - Ambil semua dokumen (dengan filter opsional)
router.get('/', async (req: Request, res: Response) => {
  try {
    const { tipe, status } = req.query;

    const where: Record<string, string> = {};
    if (tipe) where.tipe = tipe as string;
    if (status) where.status = status as string;

    const documents = await prisma.document.findMany({
      where,
      select: {
        id: true, noBerkas: true, judul: true, lokasi: true, tipe: true, 
        status: true, klasifikasi: true, keamanan: true, fileUrl: true, 
        authorId: true, createdAt: true, updatedAt: true,
        author: { select: { id: true, name: true, email: true } }
      },
      orderBy: { createdAt: 'desc' },
    });

    res.json(documents);
  } catch (error) {
    console.error('Get documents error:', error);
    res.status(500).json({ error: 'Terjadi kesalahan pada server.' });
  }
});

// POST /api/documents - Buat dokumen baru
router.post('/', upload.single('file'), async (req: Request, res: Response) => {
  try {
    const { noBerkas, judul, lokasi, tipe, status, klasifikasi, keamanan, authorId } = req.body;

    if (!noBerkas || !tipe || !authorId) {
      res.status(400).json({ error: 'noBerkas, tipe, dan authorId wajib diisi.' });
      return;
    }

    let fileData = null;
    let fileMimeType = null;
    let fileUrl = null;

    if (req.file) {
      fileData = req.file.buffer;
      fileMimeType = req.file.mimetype;
    }

    const document = await prisma.document.create({
      data: { 
        noBerkas, judul, lokasi, tipe, status, klasifikasi, keamanan, authorId, 
        fileData, fileMimeType, fileUrl 
      },
    });

    if (fileData) {
      // Update fileUrl using the actual document ID generated by database
      await prisma.document.update({
        where: { id: document.id },
        data: { fileUrl: `/api/documents/${document.id}/file` }
      });
      document.fileUrl = `/api/documents/${document.id}/file`;
    }

    // Don't send massive binary data back in JSON
    const { fileData: _, ...docWithoutData } = document as any;
    res.status(201).json(docWithoutData);
  } catch (error) {
    console.error('Create document error:', error);
    res.status(500).json({ error: 'Terjadi kesalahan pada server.' });
  }
});

// GET /api/documents/stats - Statistik dashboard
router.get('/stats', async (req: Request, res: Response) => {
  try {
    const { tipe } = req.query;

    const where: Record<string, string> = {};
    if (tipe) where.tipe = tipe as string;

    const total = await prisma.document.count({ where });
    const proses = await prisma.document.count({ where: { ...where, status: 'proses' } });
    const selesai = await prisma.document.count({ where: { ...where, status: 'selesai' } });
    const error = await prisma.document.count({ where: { ...where, status: 'error' } });

    res.json({ total, proses, selesai, error });
  } catch (error) {
    console.error('Stats error:', error);
    res.status(500).json({ error: 'Terjadi kesalahan pada server.' });
  }
});

// GET /api/documents/global-stats - Statistik grafik
router.get('/global-stats', async (req: Request, res: Response) => {
  try {
    const sengketaCount = await prisma.document.count({ where: { tipe: 'sengketa' } });
    const sengketaSelesai = await prisma.document.count({ where: { tipe: 'sengketa', status: 'selesai' } });
    const perkaraCount = await prisma.document.count({ where: { tipe: 'perkara' } });
    const perkaraProses = await prisma.document.count({ where: { tipe: 'perkara', status: 'proses' } });
    
    // Simulate trend based on created data (for now using raw query or simple counts)
    const trend = {
      sengketa: [12, 19, 15, 10, 22],
      perkara: [5, 8, 12, 6, 15]
    };

    res.json({ sengketaCount, sengketaSelesai, perkaraCount, perkaraProses, trend });
  } catch (error) {
    res.status(500).json({ error: 'Server error' });
  }
});

// GET /api/documents/export - Ekspor data ke CSV
router.get('/export', async (req: Request, res: Response) => {
  try {
    const { tipe } = req.query;
    const where: Record<string, string> = {};
    if (tipe) where.tipe = tipe as string;

    const documents = await prisma.document.findMany({
      where,
      include: { author: { select: { name: true } } },
      orderBy: { createdAt: 'desc' },
    });

    // Generate CSV
    const header = 'No,No Berkas,Judul,Lokasi,Tipe,Status,Klasifikasi,Keamanan,Petugas,Tanggal';
    const rows = documents.map((doc, i) =>
      `${i + 1},"${doc.noBerkas}","${doc.judul}","${doc.lokasi}","${doc.tipe}","${doc.status}","${doc.klasifikasi}","${doc.keamanan}","${doc.author.name}","${doc.createdAt.toISOString().split('T')[0]}"`
    );
    const csv = [header, ...rows].join('\n');

    res.setHeader('Content-Type', 'text/csv; charset=utf-8');
    res.setHeader('Content-Disposition', `attachment; filename="export_documents_${tipe || 'all'}.csv"`);
    res.send(csv);
  } catch (error) {
    console.error('Export error:', error);
    res.status(500).json({ error: 'Terjadi kesalahan pada server.' });
  }
});

// GET /api/documents/:id/file - Serve binary file data
router.get('/:id/file', async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    const document = await prisma.document.findUnique({
      where: { id }
    });

    if (!document || !document.fileData) {
      res.status(404).json({ error: 'File tidak ditemukan' });
      return;
    }

    res.setHeader('Content-Type', document.fileMimeType || 'application/pdf');
    res.send(document.fileData);
  } catch (error) {
    console.error('Fetch file error:', error);
    res.status(500).json({ error: 'Gagal mengambil file' });
  }
});

// DELETE /api/documents/:id - Hapus dokumen
router.delete('/:id', async (req: Request, res: Response) => {
  try {
    const { id } = req.params;
    await prisma.document.delete({ where: { id } });
    res.status(200).json({ message: 'Dokumen berhasil dihapus' });
  } catch (error) {
    console.error('Delete error:', error);
    res.status(500).json({ error: 'Gagal menghapus dokumen' });
  }
});

export default router;
